---
driver:
  name: docker
  hostname: telegraf.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: telegraf
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - linux.system.repo
        - telegraf
  pillars:
    top.sls:
      base:
        "*":
          - telegraf
          - linux_repo_extra
  pillars-from-files:
    linux_repo_extra.sls: tests/pillar/repo_extra.sls

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: telegraf_agent
    provisioner:
      pillars-from-files:
        telegraf.sls: tests/pillar/telegraf_agent.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
